# Generated by Django 5.2.7 on 2025-10-13 21:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, default="User", max_length=50, null=True
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, default="Account", max_length=50, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("password", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("Female", "Female"),
                            ("Male", "Male"),
                            ("Other", "Other"),
                        ],
                        default="Other",
                        max_length=10,
                    ),
                ),
                ("profile_image", models.URLField(blank=True, null=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("User", "User"),
                            ("Agent", "Agent"),
                            ("Admin", "Admin"),
                            ("Super Admin", "Super Admin"),
                        ],
                        default="User",
                        max_length=50,
                    ),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("Suspended", "Suspended"),
                            ("Verified", "Verified"),
                            ("Unverified", "Unverified"),
                            ("Deactivated", "Deactivated"),
                        ],
                        default="Unverified",
                        max_length=50,
                    ),
                ),
                (
                    "otp_token",
                    models.CharField(blank=True, max_length=6, null=True, unique=True),
                ),
                ("is_2fa_enabled", models.BooleanField(default=False)),
                ("is_email_verified", models.BooleanField(default=False)),
                ("is_admin_user", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AccountDeleteRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.TextField(blank=True, null=True)),
                ("date_requested", models.DateField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
